<?php

namespace WpBase\FindCoRating;

class Post extends WpBaseController {

    public static $config;
    
    function __construct($config) {
    
        // Set Base Post Config
        self::$config = $config;

        add_action('add_meta_boxes', [$this, 'renderVoting']);
    }

    /**
     * Adds a meta box to the post editing screen for displaying voting results.
     *
     * This function uses the add_meta_box function to add a meta box to the post editing screen.
     * The meta box has an ID of 'findco-voting-results', a title of 'Find.co Voting Results', and is displayed in the 'normal' context with 'high' priority.
     * The content of the meta box is generated by the 'renderFindcoVotingResults' method of this class.
     *
     * @return void
     */
    function renderVoting() {
        add_meta_box(
            'findco-voting-results',
            __('Find.co Voting Results', 'textdomain'),
            [$this, 'renderFindcoVotingResults'],
            'post',
            'normal',
            'high'
        );
    }

    /**
     * Renders the voting results for a specific post.
     *
     * This function retrieves the Vote controller from the DbController module and gets the vote results for the post.
     * It then outputs two read-only input fields with the positive and negative vote counts.
     *
     * @param \WP_Post $post The post to render the voting results for.
     * @return void
     */
    function renderFindcoVotingResults($post) {
        global $FindCoRating;

        if (empty($FindCoRating)) { return $content; }

        $dbModule = $FindCoRating->getModule('DbController');

        $voteTable = $dbModule->getController('Vote');

        $voteResults = $voteTable->getVoteResults($post->ID);

        echo '<div><label for="fcr-positive-votes">';
        _e('Find.co Positive Votes', 'textdomain');
        echo '</label> ';
        echo '<input type="text" readonly id="fcr-positive-votes" name="fcr_positive_votes" value="' . esc_attr($voteResults['positive']) . '" /></div>';

        echo '<div style="margin-top: 8px;"><label for="fcr-negative-votes">';
        _e('Find.co Negative Votes', 'textdomain');
        echo '</label> ';
        echo '<input type="text" readonly  id="fcr-negative-votes" name="fcr_negative_votes" value="' . esc_attr($voteResults['negative']) . '" /></div>';
    }
}

